//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchNotification.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FetchNotification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string add_lead {
            get {
                return ResourceManager.GetString("add_lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Bounce.
        /// </summary>
        public static string call_bounce {
            get {
                return ResourceManager.GetString("call_bounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message.
        /// </summary>
        public static string chat_message {
            get {
                return ResourceManager.GetString("chat_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your settings prefrences.
        /// </summary>
        public static string choose_setting {
            get {
                return ResourceManager.GetString("choose_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You connected.
        /// </summary>
        public static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string connection_fail {
            get {
                return ResourceManager.GetString("connection_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are loged with this api token.
        /// </summary>
        public static string loged_with {
            get {
                return ResourceManager.GetString("loged_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message in Mission.
        /// </summary>
        public static string mission_message {
            get {
                return ResourceManager.GetString("mission_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string new_email {
            get {
                return ResourceManager.GetString("new_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mission.
        /// </summary>
        public static string new_mission {
            get {
                return ResourceManager.GetString("new_mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past here your api_token.
        /// </summary>
        public static string paste_api_token {
            get {
                return ResourceManager.GetString("paste_api_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedualed Mission.
        /// </summary>
        public static string schedualed_mission {
            get {
                return ResourceManager.GetString("schedualed_mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Message.
        /// </summary>
        public static string service_message {
            get {
                return ResourceManager.GetString("service_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide.
        /// </summary>
        public static string show_hide {
            get {
                return ResourceManager.GetString("show_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Message.
        /// </summary>
        public static string system_message {
            get {
                return ResourceManager.GetString("system_message", resourceCulture);
            }
        }
    }
}
